name: start wireguard v2ray

on:
  schedule:
  - cron: "0 0 */1 * *"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: start wireguard and v2ray 
      run: |
        sudo apt install wireguard -y
        echo "${{ secrets.ALIYUN_SERVER_PUBKEY }} "
        
      
